nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['X-ACCESS-TOKEN', 'content-type']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        expose_headers: ['X-ACCESS-TOKEN']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': ~
#        '^/api/':
#            allow_origin: ['*']
#            allow_headers: ['X-ACCESS-TOKEN']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#        '^/':
#            origin_regex: true
#            allow_origin: ['^http://localhost:[0-9]+']
#            allow_headers: ['X-ACCESS-TOKEN']
#            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
#            max_age: 3600
#            hosts: ['^api\.']
